[package]
name = "zelda-save-shell"
version = "0.1.0"
edition = "2021"

[lib]
name = "zelda_save_shell_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = "2"

[dependencies]
save-engine = { path = "../crates/save-engine" }
serde = { version = "1", features = ["derive"] }
tauri = "2"
tauri-plugin-dialog = "2"
